name: Packer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.8

      - name: Run packer.py
        run: python source_files/packer.py
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-files
          path: ./pack.zip
